name: Firebase Function Deploy
on:
  push:
    branches: [main]
    paths:
      - "server/**"
defaults:
  run:
    working-directory: server

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm packages
        run: |
          npm install
        working-directory: ./server

      - name: Create Env File
        run: |
          touch .env
          echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} >> .env
          echo AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} >> .env
          echo JOB_SQS_URL=${{ secrets.JOB_SQS_URL }} >> .env
        working-directory: ./server

      - name: Create Firebase Credentials File
        uses: "finnp/create-file-action@76e2826db048c29ab0955dd7728016657363fb3a"
        env:
          FILE_NAME: "firebase_credentials.json"
          FILE_DATA: ${{ secrets.FIREBASE_CREDENTIALS }}

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@1e278621b8467eff7eb0248e275bef80e85360df
        with:
          args: deploy --only functions:api
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
